server.port=8080

spring.datasource.url=jdbc:postgresql://ep-dark-sky-ap6f0swr-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_9CqDIUXKMhG3

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
cloudinary.cloud_name=debvxtlcj
cloudinary.api_key=873925649595815
cloudinary.api_secret=nzOaK-1Xtdlq3fYUQIxBzAVv2QY
